
Unlock Your Potential with Skillboox
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"pBTPbg1mg4F","props":{"isLead":true},"hash":"Nv7NPdkp_"},"kubioAI":{"meta":{"initialValues":{"words":20,"chars":112}}}} -->
At Skillboox Africa, we believe that education is the key to unlocking and driving societal progress.
<!-- /wp:kubio/text -->

<!-- wp:kubio/buttongroup {"kubio":{"styleRef":"E9V2SDzWy7g","hash":"M6pPjn-QW26"}} -->
<!-- wp:kubio/button {"kubio":{"styleRef":"Z8ODkgcg9io","props":{"buttonWidth":"fitToContent","iconPosition":"before","showIcon":false,"buttonSize":"medium","horizontalAlign":"center"},"style":{"descendants":{"link":{"padding":{"top":{"unit":"px","value":16},"bottom":{"unit":"px","value":16},"left":{"unit":"px","value":32},"right":{"unit":"px","value":32}},"typography":{"size":{"unit":"px","value":14},"weight":"600","transform":"uppercase","lineHeight":{"value":"1"},"letterSpacing":{"value":"1","unit":"px"},"color":"#fff","margin":{"bottom":"2rem"}},"textAlign":"center","background":{"color":"rgba(var(--kubio-color-1),1)"},"border":{"top":{"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"},"radius":{"right":{"value":6,"unit":"px"},"left":{"value":6,"unit":"px"}}},"bottom":{"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"},"radius":{"right":{"value":6,"unit":"px"},"left":{"value":6,"unit":"px"}}},"right":{"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"}},"left":{"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"}}},"states":{"hover":{"background":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"border":{"top":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"right":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"bottom":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"left":{"color":"rgba(var(--kubio-color-1-variant-4),1)"}}}}},"icon":{"size":{"unit":"px","value":"12"},"margin":{"left":{"value":"0","unit":"px"},"right":{"value":"10","unit":"px"}}}}},"hash":"jsSdPuKorbP"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"preserveSpace":{"text":false},"icon":{"name":"font-awesome/star"}} -->
Explore Our Courses
<!-- /wp:kubio/button -->
<!-- /wp:kubio/buttongroup -->
<!-- /wp:kubio/column -->
<!-- /wp:kubio/row -->

<!-- wp:kubio/row {"kubio":{"styleRef":"a89Nj9qMZeO","props":{"fullBackground":false,"layout":{"equalWidth":false,"equalHeight":false,"itemsPerRow":2,"verticalAlign":"end","horizontalAlign":"center","horizontalGap":0,"verticalGap":0,"horizontalInnerGap":2,"verticalInnerGap":2,"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}}},"media":{"mobile":{"layout":{"itemsPerRow":3,"horizontalGap":0,"outerGapLinked":false,"equalWidth":false}}}},"style":{"descendants":{"container":{"padding":{"top":{"value":"20","unit":"px"},"right":{"unit":"px"},"bottom":{"unit":"px"},"left":{"unit":"px"}}}}},"hash":"sk4TKyNw95R"}} -->
<!-- wp:kubio/column {"kubio":{"styleRef":"HCDFfAZnFqk","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"center","verticalInnerGap":0,"horizontalInnerGap":0},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"center","customHeight":{"type":"min-height","min-height":{"value":350,"unit":"px"}},"background":{"color":"rgba(134, 69, 69, 0)","type":"image","image":[{"source":{"type":"image","url":"https://skillbooxafrica.com/wp-content/uploads/2024/06/Untitled-design-55.png"},"position":{"x":50,"y":59}}]},"boxShadow":{"enabled":false,"layers":[{"spread":"0","y":"-10","blur":"18","color":"rgba(0, 0, 0, 0.16)","x":"0","inset":""}]},"border":{"top":{"radius":{"left":{"value":6,"unit":"px"},"right":{"value":6,"unit":"px"}}},"bottom":{"radius":{"left":{"unit":"px"},"right":{"unit":"px"}}}},"media":{"tablet":{"customHeight":{"min-height":{"value":250,"unit":"px"},"type":"min-height"}},"mobile":{"customHeight":{"min-height":{"value":250,"unit":"px"},"type":"min-height"}}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":90,"unit":"%"}}},"tablet":{"columnWidth":{"custom":{"value":100,"unit":"%"},"type":"custom"}}},"columnWidth":{"type":"custom","custom":{"unit":"%","value":100}}}}},"hash":"nflUGW3yR"},"kubioAI":{"imageTerms":"learning education diversity"}} /-->
<!-- /wp:kubio/row -->
<!-- /wp:kubio/section -->

<!-- wp:kubio/section {"kubio":{"styleRef":"WjGXiQqXAYA","hash":"Hh-OYZY-N1k","style":{"descendants":{"outer":{"background":{"color":"rgba(var(--kubio-color-5),1)"}}}}},"attrs":{"name":"Content"},"anchor":"content","kubioAI":{"meta":{"category":"content","cloudPresetId":804,"summary":"Diverse course categories to meet wide range of learners' needs"}}} -->
<!-- wp:kubio/row {"kubio":{"styleRef":"mtY0XvEtoh6","props":{"layout":{"itemsPerRow":2,"custom":[{"type":"custom","custom":{"value":33.3299999999999982946974341757595539093017578125,"unit":"%"}},{"type":"custom","custom":{"value":66.659999999999996589394868351519107818603515625,"unit":"%"}}],"equalHeight":true,"equalWidth":false,"verticalGap":3,"horizontalGap":3},"media":{"mobile":{"layout":{"horizontalGap":3}}}},"hash":"Z3mCqqezxa9"}} -->
<!-- wp:kubio/column {"kubio":{"styleRef":"IUl0ovMj60b","_style":{"descendants":{"container":{"columnWidth":{"type":"custom","custom":{"value":40,"unit":"%"}}}}},"hash":"x9dK0U44PJk","style":{"descendants":{"inner":{"textAlign":"left"}}},"props":{"layout":{"horizontalInnerGap":3,"verticalInnerGap":3,"verticalAlign":"center"}}}} -->
<!-- wp:kubio/heading {"kubio":{"styleRef":"H2iktXvp2-g","props":{"level":4,"fancy":{"fancyRotatingWords":"awesome\namazing\nimpressive"}},"hash":"AeADDx9RuQr"},"kubioAI":{"meta":{"initialValues":{"words":9,"chars":58}}}} -->
Why Choose Skillboox
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"6LJ0-P7ECL8","hash":"B-_Bp0MlZ","style":{"descendants":{"text":{"typography":{"color":"rgba(var(--kubio-color-6),1)"},"textAlign":"justify"}}},"props":{"isLead":false}},"kubioAI":{"meta":{"initialValues":{"words":35,"chars":179}}}} -->
At Skillboox, we understand that every learner has unique needs and goals. No matter what your interests or career aspirations may be, we have something to offer you.  We aim to bridge the skills gap, contributing to the overall development and prosperity of Africa.
<!-- /wp:kubio/text -->
<!-- /wp:kubio/column -->

<!-- wp:kubio/column {"kubio":{"styleRef":"oGDxWbcttNy","_style":{"descendants":{"container":{"columnWidth":{"type":"custom","custom":{"value":60,"unit":"%"}}}}},"hash":"xYqYISp5b","style":{"descendants":{"inner":{"border":{"top":{"radius":{"left":{"value":6,"unit":"px"},"right":{"value":6,"unit":"px"}}},"bottom":{"radius":{"right":{"value":6,"unit":"px"},"left":{"value":6,"unit":"px"}}}},"background":{"type":"image","image":[{"source":{"type":"image","url":"https://skillbooxafrica.com/wp-content/uploads/2024/06/Untitled-design-51.png"},"position":{"x":50,"y":50}}]},"customHeight":{"type":"min-height","min-height":{"value":350,"unit":"px"}}}}}},"kubioAI":{"imageTerms":"online courses technology virtual learning"}} /-->
<!-- /wp:kubio/row -->

<!-- wp:kubio/row {"kubio":{"styleRef":"mtY0XvEtoh6","props":{"layout":{"itemsPerRow":2,"custom":[{"type":"custom","custom":{"value":33.3299999999999982946974341757595539093017578125,"unit":"%"}},{"type":"custom","custom":{"value":66.659999999999996589394868351519107818603515625,"unit":"%"}}],"equalHeight":true,"equalWidth":false,"verticalGap":3,"horizontalGap":3},"media":{"mobile":{"layout":{"horizontalGap":3}}}},"hash":"uSud21A9j17"}} -->
<!-- wp:kubio/column {"kubio":{"styleRef":"npDyE3Sc8zW","_style":{"descendants":{"container":{"columnWidth":{"type":"custom","custom":{"value":60,"unit":"%"}}}}},"hash":"_bdETd2ws","style":{"descendants":{"inner":{"border":{"top":{"radius":{"left":{"value":6,"unit":"px"},"right":{"value":6,"unit":"px"}}},"bottom":{"radius":{"right":{"value":6,"unit":"px"},"left":{"value":6,"unit":"px"}}}},"background":{"type":"image","image":[{"source":{"type":"image","url":"https://skillbooxafrica.com/wp-content/uploads/2024/06/Untitled-design-52.png"},"position":{"x":50,"y":50}}]},"customHeight":{"type":"min-height","min-height":{"value":350,"unit":"px"}}}}}},"kubioAI":{"imageTerms":"classroom vocational training hands on learning"}} /-->

<!-- wp:kubio/column {"kubio":{"styleRef":"IUl0ovMj60b","_style":{"descendants":{"container":{"columnWidth":{"type":"custom","custom":{"value":40,"unit":"%"}}}}},"hash":"ymxjFCuTnFO","style":{"descendants":{"inner":{"textAlign":"left"}}},"props":{"layout":{"horizontalInnerGap":3,"verticalInnerGap":3,"verticalAlign":"center"}}}} -->
<!-- wp:kubio/heading {"kubio":{"styleRef":"H2iktXvp2-g","props":{"level":4,"fancy":{"fancyRotatingWords":"awesome\namazing\nimpressive"}},"hash":"ly1jfl4ZovD"},"kubioAI":{"meta":{"initialValues":{"words":9,"chars":58}}}} -->
Why Train with Us
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"6LJ0-P7ECL8","hash":"-txF_fhsL","style":{"descendants":{"text":{"typography":{"color":"rgba(var(--kubio-color-6),1)"},"textAlign":"justify"}}},"props":{"isLead":false}},"kubioAI":{"meta":{"initialValues":{"words":35,"chars":179}}}} -->
Our diverse range of courses is designed to equip you with the skills you need for immediate success and long-term growth. Whether you're looking to enhance your current career or embark on a new path, our expert trainers and comprehensive programs will guide you every step of the way.
<!-- /wp:kubio/text -->
<!-- /wp:kubio/column -->
<!-- /wp:kubio/row -->
<!-- /wp:kubio/section -->

<!-- wp:kubio/section {"kubio":{"styleRef":"XwtrGTaWrqN","props":{"width":"full-width","verticalAlign":"center","showHeader":false,"overlapSection":false,"attrs":{"name":"blank","id":"blank","overflowOption":"hidden"}},"style":{"descendants":{"outer":{"customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"background":{"overlay":{"enabled":false,"type":"shapeOnly","shape":{"value":"two-circles","isTile":false}},"color":"rgba(var(--kubio-color-5),1)"},"separators":{"bottom":{"color":"rgba(var(--kubio-color-1),1)","enabled":false,"type":"opacity-tilt","negative":false,"height":{"value":300}},"top":{"color":"rgba(var(--kubio-color-1),1)","enabled":false,"type":"opacity-tilt","negative":false,"height":{"value":300}}}}}},"hash":"kuZHBeglkzU"},"attrs":{"name":"Content 1"},"anchor":"content-1","kubioAI":{"meta":{"category":"content","cloudPresetId":1170,"summary":"Professional and accredited certifications for career advancement."}}} -->
<!-- wp:kubio/row {"kubio":{"styleRef":"ZPfofNxbC8W","props":{"fullBackground":false,"layout":{"equalWidth":false,"equalHeight":true,"itemsPerRow":2,"verticalAlign":"center","horizontalAlign":"center","horizontalGap":0,"verticalGap":0,"horizontalInnerGap":2,"verticalInnerGap":2,"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}}},"media":{"mobile":{"layout":{"itemsPerRow":1,"horizontalGap":2,"outerGapLinked":false,"verticalGap":2}}}},"hash":"2oJCtfxfaLm"}} -->
<!-- wp:kubio/column {"kubio":{"styleRef":"WaXIWUnjiEL","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"start","verticalInnerGap":0,"horizontalInnerGap":0},"media":{"mobile":{"layout":{"verticalInnerGap":0,"horizontalInnerGap":0}}},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"center","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"background":{"type":"image","image":[{"source":{"type":"image","url":"https://skillbooxafrica.com/wp-content/uploads/2024/06/Untitled-design-53.png"},"position":{"x":50,"y":50}}]},"boxShadow":{"enabled":false,"layers":[{"y":"19","spread":"0","blur":"38","color":"rgba(0, 0, 0, 0.16)","x":"0","inset":""}]},"media":{"mobile":{"customHeight":{"type":"min-height","min-height":{"value":"400"}}}}},"container":{"media":{"mobile":{"padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":100,"unit":"%"}}}},"columnWidth":{"type":"custom","custom":{"unit":"%","value":"40"}}}}},"hash":"Nw8BJLoU7"},"kubioAI":{"imageTerms":"professional career advancement certifications"}} /-->

<!-- wp:kubio/column {"kubio":{"styleRef":"NKDrja5D948","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"start","verticalInnerGap":0,"horizontalInnerGap":0},"media":{"mobile":{"layout":{"horizontalInnerGap":0}}},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"left","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"padding":{"top":{"value":"5","unit":"%"},"right":{"value":"12","unit":"%"},"bottom":{"value":"5","unit":"%"},"left":{"value":"17","unit":"%"}},"media":{"tablet":{"padding":{"top":{"value":"5","unit":"%"},"right":{"value":"5","unit":"%"},"bottom":{"value":"5","unit":"%"},"left":{"value":"10","unit":"%"}}},"mobile":{"padding":{"top":{"value":"15","unit":"px"},"right":{"value":"15","unit":"px"},"bottom":{"value":"15","unit":"px"},"left":{"value":"15","unit":"px"}},"textAlign":"center"}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":100,"unit":"%"}}}},"columnWidth":{"type":"custom","custom":{"unit":"%","value":"60"}}}}},"hash":"vaGd0bDZhBa"}} -->
<!-- wp:kubio/heading {"kubio":{"styleRef":"iqdrlwqzUr6","props":{"fancy":{"fancyWord":"awesome","fancyRotatingWords":"beautiful\namazing\nimpressive","typeStyle":"none","typeShape":"curly","typeAnimation":"rotate-1","bringToFront":false,"useRoundedEdges":false,"animationDuration":{"value":"1","unit":"s"},"type":{"animationDuration":{"in":{"value":"0.1","unit":"s"},"out":{"value":"0.1","unit":"s"}}}},"level":5},"style":{"descendants":{"text":{"typography":{"transform":"uppercase","color":"rgba(var(--kubio-color-1),1)"}},"svgShape":{"stroke":{"width":{"value":"8","unit":"px"},"color":"#000000"}}}},"hash":"3160QetUcHV"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"kubioAI":{"meta":{"initialValues":{"words":3,"chars":15}}}} -->
Enhance Your Skills with Accredited Certifications
<!-- /wp:kubio/heading -->

<!-- wp:kubio/heading {"kubio":{"props":{"fancy":{"fancyWord":"awesome","fancyRotatingWords":"beautiful\namazing\nimpressive","typeStyle":"none","typeShape":"curly","typeAnimation":"rotate-1","bringToFront":false,"useRoundedEdges":false,"animationDuration":{"value":"1","unit":"s"},"type":{"animationDuration":{"in":{"value":"0.1","unit":"s"},"out":{"value":"0.1","unit":"s"}}}},"level":2},"style":{"descendants":{"svgShape":{"stroke":{"width":{"value":"8","unit":"px"},"color":"#000000"}}}},"styleRef":"wP8zgeaiXYJ","hash":"xjrwzj7JOvN"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"kubioAI":{"meta":{"initialValues":{"words":4,"chars":18}}}} -->
Trusted and Valued by Employers
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"Kavj0EHyciJ","props":{"type":"normal"},"hash":"bx6PpXjyFxE"},"kubioAI":{"meta":{"initialValues":{"words":36,"chars":192}}}} -->
At Skillboox Africa, we understand the value of professional and accredited certifications for career advancement. That's why we offer a wide range of courses in different categories to help learners build their skills and expertise.
<!-- /wp:kubio/text -->

<!-- wp:kubio/row {"kubio":{"styleRef":"Qvxtg4oi3Z1","props":{"fullBackground":false,"layout":{"equalWidth":true,"equalHeight":true,"itemsPerRow":2,"verticalAlign":"center","horizontalAlign":"center","horizontalGap":2,"verticalGap":2,"horizontalInnerGap":0,"verticalInnerGap":0,"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}}},"media":{"mobile":{"layout":{"itemsPerRow":2,"horizontalGap":0,"outerGapLinked":false,"horizontalAlign":"center","verticalGap":0}}}},"style":{"descendants":{"container":{"padding":{"top":{"unit":"px"},"right":{"unit":"px"},"bottom":{"unit":"px"},"left":{"unit":"px"}},"margin":{"top":{"unit":"px"},"right":{"unit":"px"},"bottom":{"unit":"px"},"left":{"value":"-15","unit":"px"}},"media":{"tablet":{"margin":{"top":{"unit":"px"},"right":{"unit":"px"},"bottom":{"unit":"px"},"left":{"value":"-10","unit":"px"}}},"mobile":{"margin":{"top":{"unit":"px"},"right":{"unit":"px"},"bottom":{"unit":"px"},"left":{"value":"0","unit":"px"}}}}}}},"hash":"a8ztvO9WOnQ"}} -->
<!-- wp:kubio/column {"kubio":{"styleRef":"9BE2vO78N03","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"start","verticalInnerGap":1,"horizontalInnerGap":0,"vSpace":{"value":0,"unit":"px"}},"media":{"mobile":{"layout":{"vSpace":{"value":"10"},"verticalInnerGap":2,"horizontalInnerGap":2}}},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"left","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"media":{"mobile":{"textAlign":"center","padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}},"container":{"media":{"mobile":{"padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":100,"unit":"%"}}}}}}},"hash":"gh9ZYvQdwPh"}} -->
<!-- wp:kubio/heading {"kubio":{"styleRef":"GqLPWidLeR_","props":{"fancy":{"fancyWord":"awesome","fancyRotatingWords":"beautiful\namazing\nimpressive","typeStyle":"none","typeShape":"curly","typeAnimation":"rotate-1","bringToFront":false,"useRoundedEdges":false,"animationDuration":{"value":"1","unit":"s"},"type":{"animationDuration":{"in":{"value":"0.1","unit":"s"},"out":{"value":"0.1","unit":"s"}}}},"level":5},"style":{"descendants":{"svgShape":{"stroke":{"width":{"value":"8","unit":"px"},"color":"#000000"}}}},"hash":"rxvQYeIMnJ2"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"kubioAI":{"meta":{"initialValues":{"words":2,"chars":10}}}} -->
Expert Instructors Dedicated to Your Success
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"fluulMpF7r5","props":{"type":"normal"},"hash":"Nneyd3Qzk","style":{"descendants":{"text":{"textAlign":"justify"}}}},"kubioAI":{"meta":{"initialValues":{"words":10,"chars":51}}}} -->
Our team of instructors is made up of experienced professionals and industry experts who are passionate about sharing their knowledge and skills with others.
<!-- /wp:kubio/text -->
<!-- /wp:kubio/column -->

<!-- wp:kubio/column {"kubio":{"styleRef":"9BE2vO78N03","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"start","verticalInnerGap":1,"horizontalInnerGap":0,"vSpace":{"value":0,"unit":"px"}},"media":{"mobile":{"layout":{"vSpace":{"value":"10"},"verticalInnerGap":2,"horizontalInnerGap":2}}},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"left","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"media":{"mobile":{"textAlign":"center","padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}},"container":{"media":{"mobile":{"padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":100,"unit":"%"}}}}}}},"hash":"Ol79Fx04CY8"}} -->
<!-- wp:kubio/heading {"kubio":{"props":{"fancy":{"fancyWord":"awesome","fancyRotatingWords":"beautiful\namazing\nimpressive","typeStyle":"none","typeShape":"curly","typeAnimation":"rotate-1","bringToFront":false,"useRoundedEdges":false,"animationDuration":{"value":"1","unit":"s"},"type":{"animationDuration":{"in":{"value":"0.1","unit":"s"},"out":{"value":"0.1","unit":"s"}}}},"level":5},"style":{"descendants":{"svgShape":{"stroke":{"width":{"value":"8","unit":"px"},"color":"#000000"}}}},"styleRef":"GqLPWidLeR_","hash":"0D4eeRQykVl"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"kubioAI":{"meta":{"initialValues":{"words":2,"chars":10}}}} -->
Accessible Education for All
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"fluulMpF7r5","props":{"type":"normal"},"hash":"_Oy_iqhLZq","style":{"descendants":{"text":{"textAlign":"justify"}}}},"kubioAI":{"meta":{"initialValues":{"words":10,"chars":51}}}} -->
We believe that education should be accessible and convenient. By combining accessibility and convenience, we are empowering individuals to improve their career prospects, and achieve their professional goals.
<!-- /wp:kubio/text -->
<!-- /wp:kubio/column -->

<!-- wp:kubio/column {"kubio":{"styleRef":"9BE2vO78N03","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"start","verticalInnerGap":1,"horizontalInnerGap":0,"vSpace":{"value":0,"unit":"px"}},"media":{"mobile":{"layout":{"vSpace":{"value":"10"},"verticalInnerGap":2,"horizontalInnerGap":2}}},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"left","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"media":{"mobile":{"textAlign":"center","padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}},"container":{"media":{"mobile":{"padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":100,"unit":"%"}}}}}}},"hash":"ol8PBqWYIlE"}} -->
<!-- wp:kubio/heading {"kubio":{"props":{"fancy":{"fancyWord":"awesome","fancyRotatingWords":"beautiful\namazing\nimpressive","typeStyle":"none","typeShape":"curly","typeAnimation":"rotate-1","bringToFront":false,"useRoundedEdges":false,"animationDuration":{"value":"1","unit":"s"},"type":{"animationDuration":{"in":{"value":"0.1","unit":"s"},"out":{"value":"0.1","unit":"s"}}}},"level":5},"style":{"descendants":{"svgShape":{"stroke":{"width":{"value":"8","unit":"px"},"color":"#000000"}}}},"styleRef":"GqLPWidLeR_","hash":"wY1ZtCDSAEH"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"kubioAI":{"meta":{"initialValues":{"words":2,"chars":10}}}} -->
Diverse Course Categories for Every Interest
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"fluulMpF7r5","props":{"type":"normal"},"hash":"3ZHJ-8wZVa","style":{"descendants":{"text":{"textAlign":"justify"}}}},"kubioAI":{"meta":{"initialValues":{"words":10,"chars":51}}}} -->
From tech and creative arts to vocational training and personal development, we offer a comprehensive range of course categories to cater to diverse interests and professional needs.
<!-- /wp:kubio/text -->
<!-- /wp:kubio/column -->

<!-- wp:kubio/column {"kubio":{"styleRef":"9BE2vO78N03","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"start","verticalInnerGap":1,"horizontalInnerGap":0,"vSpace":{"value":0,"unit":"px"}},"media":{"mobile":{"layout":{"vSpace":{"value":"10"},"verticalInnerGap":2,"horizontalInnerGap":2}}},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"left","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"media":{"mobile":{"textAlign":"center","padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}},"container":{"media":{"mobile":{"padding":{"left":{"unit":"px"},"right":{"unit":"px"},"top":{"unit":"px"},"bottom":{"unit":"px"}}}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":100,"unit":"%"}}}}}}},"hash":"Q-jNeYhQ5fY"}} -->
<!-- wp:kubio/heading {"kubio":{"props":{"fancy":{"fancyWord":"awesome","fancyRotatingWords":"beautiful\namazing\nimpressive","typeStyle":"none","typeShape":"curly","typeAnimation":"rotate-1","bringToFront":false,"useRoundedEdges":false,"animationDuration":{"value":"1","unit":"s"},"type":{"animationDuration":{"in":{"value":"0.1","unit":"s"},"out":{"value":"0.1","unit":"s"}}}},"level":5},"style":{"descendants":{"svgShape":{"stroke":{"width":{"value":"8","unit":"px"},"color":"#000000"}}}},"styleRef":"GqLPWidLeR_","hash":"2qNzn-XSAf_"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"kubioAI":{"meta":{"initialValues":{"words":2,"chars":10}}}} -->
Get Ahead in Your Career
<!-- /wp:kubio/heading -->

<!-- wp:kubio/text {"kubio":{"styleRef":"fluulMpF7r5","props":{"type":"normal"},"hash":"YxZfdKbGtm","style":{"descendants":{"text":{"textAlign":"justify"}}}},"kubioAI":{"meta":{"initialValues":{"words":10,"chars":51}}}} -->
With our professional and accredited certifications, you can stand out to potential employers and take your career to the next level.
<!-- /wp:kubio/text -->
<!-- /wp:kubio/column -->
<!-- /wp:kubio/row -->
<!-- /wp:kubio/column -->
<!-- /wp:kubio/row -->
<!-- /wp:kubio/section -->

<!-- wp:kubio/section {"kubio":{"styleRef":"G9X3bFbx5DK","props":{"width":"boxed","verticalAlign":"center","showHeader":false,"overlapSection":false,"attrs":{"name":"blank","id":"blank"}},"style":{"descendants":{"outer":{"customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"background":{"type":"image","image":[{"source":{"type":"image","url":"https://skillbooxafrica.com/wp-content/uploads/2024/06/Untitled-design-56.png"},"position":{"x":50.62155872168927572829488781280815601348876953125,"y":35.4246425501992376894122571684420108795166015625},"attachment":"scroll","useParallax":true,"useFeaturedImage":false}],"overlay":{"enabled":false,"color":{"opacity":0.2399999999999999911182158029987476766109466552734375}}},"separators":{"bottom":{"color":"rgba(var(--kubio-color-1),1)"},"top":{"color":"rgba(var(--kubio-color-1),1)"}},"media":{"tablet":{"background":{"image":[{"useParallax":false}]}},"mobile":{"background":{"image":[{"useParallax":false}]}}}}}},"hash":"MLptHXmXeN"},"attrs":{"name":"Call To Action"},"anchor":"call-to-action","kubioAI":{"meta":{"category":"cta","cloudPresetId":106,"summary":"Start your learning journey with Skillboox Africa today!"},"imageTerms":"online learning e learning education"}} -->
<!-- wp:kubio/row {"kubio":{"styleRef":"I50yB-lF6mP","props":{"fullBackground":false,"layout":{"equalWidth":false,"equalHeight":true,"itemsPerRow":2,"verticalAlign":"center","horizontalAlign":"center","horizontalGap":0,"verticalGap":0,"horizontalInnerGap":2,"verticalInnerGap":2,"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}}},"media":{"mobile":{"layout":{"itemsPerRow":1,"horizontalGap":0,"outerGapLinked":false}}}},"hash":"ox2DAuUQGGh"}} -->
<!-- wp:kubio/column {"kubio":{"styleRef":"ddWg7MGi_sM","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"vSpace":{"value":"15"},"verticalAlign":"start","verticalInnerGap":0,"horizontalInnerGap":0},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"center","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"background":{"color":"rgba(var(--kubio-color-5),1)"},"margin":{"top":{"value":"20","unit":"px"},"right":{"unit":"px"},"bottom":{"unit":"px"},"left":{"unit":"px"}},"padding":{"top":{"value":"5","unit":"rem"},"right":{"value":"5","unit":"rem"},"bottom":{"value":"5","unit":"rem"},"left":{"value":"5","unit":"rem"}},"media":{"mobile":{"padding":{"top":{"value":"3","unit":"rem"},"right":{"value":"3","unit":"rem"},"bottom":{"value":"3","unit":"rem"},"left":{"value":"3","unit":"rem"}}}},"border":{"top":{"radius":{"left":{"value":6,"unit":"px"},"right":{"value":6,"unit":"px"}}},"bottom":{"radius":{"right":{"value":6,"unit":"px"},"left":{"value":6,"unit":"px"}}}}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":"80","unit":"%"}}},"tablet":{"columnWidth":{"custom":{"value":"80"}}}},"columnWidth":{"type":"custom","custom":{"unit":"%","value":"60"}}}}},"hash":"d_4lLtm6yVe"}} -->
<!-- wp:kubio/heading {"kubio":{"styleRef":"ZTfSavC-VRG","props":{"fancy":{"fancyWord":"awesome","fancyRotatingWords":"beautiful\namazing\nimpressive","typeStyle":"none","typeShape":"curly","typeAnimation":"rotate-1","bringToFront":false,"useRoundedEdges":false,"animationDuration":{"value":"1","unit":"s"},"type":{"animationDuration":{"in":{"value":"0.1","unit":"s"},"out":{"value":"0.1","unit":"s"}}}},"level":2},"style":{"descendants":{"text":{"typography":{"weight":"700","family":"Playfair Display"}},"svgShape":{"stroke":{"width":{"value":"8","unit":"px"},"color":"#000000"}}}},"hash":"pWCT87Rrtd"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"kubioAI":{"meta":{"initialValues":{"words":3,"chars":11}}}} -->
Start your teaching journey with Skillboox Africa today!
<!-- /wp:kubio/heading -->

<!-- wp:kubio/icon {"kubio":{"styleRef":"oHM_0wVr_H_","props":{"horizontalAlign":"center"},"style":{"descendants":{"inner":{"fill":"rgba(var(--kubio-color-1),1)","width":{"value":"60","unit":"px"},"height":{"value":"60","unit":"px"},"states":{"hover":{"fill":"rgba(var(--kubio-color-1-variant-4),1)"}}}}},"hash":"iSAnobw9NGX"},"link":{"value":"","typeOpenLink":"sameWindow","noFollow":false,"lightboxMedia":""},"name":"icons8-line-awesome/laptop"} /-->

<!-- wp:kubio/text {"kubio":{"styleRef":"58PhObTIq2W","props":{"type":"normal"},"style":{"descendants":{"text":{"typography":{"color":"rgba(var(--kubio-color-6),1)"}}}},"hash":"VMX9eOhc4OB"},"kubioAI":{"meta":{"initialValues":{"words":26,"chars":141}}}} -->
Join Skillboox Africa and gain access to a diverse range of courses taught by experienced professionals and industry experts.
<!-- /wp:kubio/text -->
<!-- /wp:kubio/column -->

<!-- wp:kubio/column {"kubio":{"styleRef":"wEZTPyLa6Zb","props":{"layout":{"custom":{"horizontalGap":{"unit":"px","value":""},"verticalGap":{"unit":"px","value":""},"horizontalInnerGap":{"unit":"px","value":""},"verticalInnerGap":{"unit":"px","value":""}},"verticalAlign":"start","verticalInnerGap":0,"horizontalInnerGap":0},"internal":{"heroSection":{"type":null}}},"style":{"descendants":{"inner":{"textAlign":"center","customHeight":{"type":"fit-to-content","min-height":{"value":"","unit":"px"}},"transform":{"translate":[{"axis":"x","value":{"value":0,"unit":"%"}},{"axis":"y","value":{"value":"-50","unit":"%"}},{"axis":"z"}]}}}},"_style":{"descendants":{"container":{"media":{"mobile":{"columnWidth":{"type":"custom","custom":{"value":"80","unit":"%"}}},"tablet":{"columnWidth":{"custom":{"value":"70"}}}},"columnWidth":{"type":"custom","custom":{"unit":"%","value":"60"}}}}},"hash":"22Op6Mp9ypC"}} -->
<!-- wp:kubio/buttongroup {"kubio":{"styleRef":"tsCfrkjFIeF","hash":"VxMfn6OqPZl"}} -->
<!-- wp:kubio/button {"kubio":{"styleRef":"HVN8_Yudkrf","props":{"buttonWidth":"fitToContent","iconPosition":"before","showIcon":false,"buttonSize":"large","horizontalAlign":"center"},"style":{"descendants":{"link":{"padding":{"top":{"unit":"px","value":"15"},"bottom":{"unit":"px","value":"15"},"left":{"unit":"px","value":"30"},"right":{"unit":"px","value":"30"}},"typography":{"size":{"unit":"px","value":"14"},"weight":"600","transform":"uppercase","lineHeight":{"value":"1","unit":""},"letterSpacing":{"value":"1","unit":"px"},"color":"#fff","family":"Open Sans","margin":{"top":"","bottom":"2rem"}},"border":{"top":{"radius":{"right":{"value":6,"unit":"px"},"left":{"value":6,"unit":"px"}},"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"}},"bottom":{"radius":{"right":{"value":6,"unit":"px"},"left":{"value":6,"unit":"px"}},"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"}},"right":{"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"}},"left":{"color":"rgba(var(--kubio-color-1),1)","style":"solid","width":{"value":"2","unit":"px"}}},"textAlign":"center","background":{"color":"rgba(var(--kubio-color-1),1)"},"states":{"hover":{"background":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"border":{"top":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"right":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"bottom":{"color":"rgba(var(--kubio-color-1-variant-4),1)"},"left":{"color":"rgba(var(--kubio-color-1-variant-4),1)"}}}}},"icon":{"size":{"unit":"px","value":"14"},"margin":{"left":{"value":"0","unit":"px"},"right":{"value":"10","unit":"px"}}}}},"hash":"qBJElXMTH"},"link":{"value":"https://skillbooxafrica.com/teach-on-skillboox/","typeOpenLink":"newWindow","noFollow":false,"lightboxMedia":""},"preserveSpace":{"text":false},"icon":{"name":"font-awesome/star"}} -->
Start Teaching
<!-- /wp:kubio/button -->
<!-- /wp:kubio/buttongroup -->
<!-- /wp:kubio/column -->
<!-- /wp:kubio/row -->
<!-- /wp:kubio/section -->
